# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    profiles:
        active: prod
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    datasource:
        driver-class-name: org.postgresql.ds.PGSimpleDataSource
        url: jdbc:postgresql://localhost:5432/portal
        name:
        username: portal
        password: portal
    jpa:
        database-platform: co.frigorificosble.portal.domain.util.FixedPostgreSQL82Dialect
        database: POSTGRESQL
        show_sql: false
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
    mail:
        host: mail.frigorificosble.com
        port: 25
        username: trazabilidad@frigorificosble.com
        password: traza2016
        protocol: smtp        
        properties:
            mail.smtp.auth: true  
            mail.smtp.starttls.enable: false
            #mail.smtp.ssl.enable: true  
            #mail.smtp.socketFactory.port: 587
            #mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
            #mail.smtp.socketFactory.fallback: false
    thymeleaf:
        cache: true

liquibase:
    contexts: prod

server:
    port: 8080
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    frigorificosBle:
        host: http://181.48.101.158/
    http:
        cache: # Used by the CachingHttpHeadersFilter
            timeToLiveInDays: 31
    cache: # Hibernate 2nd level cache, used by CacheConfiguration
        timeToLiveSeconds: 3600
        ehcache:
            maxBytesLocalHeap: 256M
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: trazabilidad@frigorificosble.com
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        spark:
            enabled: false
            host: localhost
            port: 9999
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: PortalWeb
